<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Please sign in</h3>
            </div>
            <div class="panel-body">
                <?php
                    $form->setAttribute('method', 'post')->setAttribute('autocomplete', 'off');
                    $form->prepare();
                ?>
                <?= $this->form()->openTag($form); ?>
                <fieldset>
                    <div class="form-group <?= !empty($form->get('email')->getMessages()) ? 'has-error' : null; ?>">
                        <?= $this->formInput($form->get('email')); ?>
                        <?= $this->formelementerrors($form->get('email')) ?>
                    </div>

                    <div class="form-group <?= !empty($form->get('password')->getMessages()) ? 'has-error' : null; ?>">
                        <?= $this->formInput($form->get('password')); ?>
                        <?= $this->formelementerrors($form->get('password')) ?>
                    </div>
                    <?= $this->formElement($form->get('submit')); ?>
                </fieldset>     
                <?= $this->formElement($form->get('security')); ?>          
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>